; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = drv8833_test

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

[env:uno_prototype]
platform = atmelavr
board = uno
framework = arduino
build_src_filter = -<*> +<../prototyping/bts7960b_test.cpp>

[env:bts7960_1motor]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = -<*> +<../prototyping/bts7960b_test.cpp>

[env:pid_learning_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_deps = br3ttb/PID@^1.2.1
build_src_filter = -<*> +<../prototyping/pid_learning_test.cpp>

[env:drv8833_encoder_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_src_filter = -<*> +<../prototyping/drv8833_encoder_test.cpp>

[env:drv8833_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
build_src_filter = -<*> +<../prototyping/drv8833_test.cpp>

[env:strain_gauge_test]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_deps = bogde/HX711@^0.7.5
build_src_filter = -<*> +<../prototyping/strain_gauge_test.cpp>

[env:strain_gauge_teleplot]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_deps = bogde/HX711@^0.7.5
build_src_filter = -<*> +<../prototyping/strain_gauge_teleplot.cpp>